//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Baiguzin41size
{
    #region Контексты
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    public partial class Baiguzin41Size_ModelContainer : ObjectContext
    {
        #region Конструкторы
    
        /// <summary>
        /// Инициализирует новый объект Baiguzin41Size_ModelContainer, используя строку соединения из раздела "Baiguzin41Size_ModelContainer" файла конфигурации приложения.
        /// </summary>
        public Baiguzin41Size_ModelContainer() : base("name=Baiguzin41Size_ModelContainer", "Baiguzin41Size_ModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Инициализация нового объекта Baiguzin41Size_ModelContainer.
        /// </summary>
        public Baiguzin41Size_ModelContainer(string connectionString) : base(connectionString, "Baiguzin41Size_ModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Инициализация нового объекта Baiguzin41Size_ModelContainer.
        /// </summary>
        public Baiguzin41Size_ModelContainer(EntityConnection connection) : base(connection, "Baiguzin41Size_ModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Разделяемые методы
    
        partial void OnContextCreated();
    
        #endregion
    
    }

    #endregion

}
