//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baiguzin41size
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIckUpPoint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PIckUpPoint()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int PickupPointId { get; set; }
        public string PickupPointIndex { get; set; }
        public string PickupPointLocality { get; set; }
        public string PickupPointStreet { get; set; }
        public Nullable<int> PickupPointHouseNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
